In [2]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.feature_extraction.text import CountVectorizer
text=["London Paris London","Paris Paris London"]

In [3]:
cv=CountVectorizer()

In [4]:
count_matrix=cv.fit_transform(text)

In [5]:
count_matrix.toarray()

array([[2, 1],
       [1, 2]])

In [6]:
cv.get_feature_names()

['london', 'paris']

In [8]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics.pairwise import cosine_distances

In [9]:
cosine_similarity(count_matrix)

array([[1. , 0.8],
       [0.8, 1. ]])

In [8]:
cosine_distances(count_matrix)

array([[0. , 0.2],
       [0.2, 0. ]])

In [10]:
df=pd.read_csv("movie_dataset.csv")

In [28]:
df.head()

index  budget                         genres  \
4798   4798  220000          Action Crime Thriller   
4799   4799    9000                 Comedy Romance   
4800   4800       0  Comedy Drama Romance TV Movie   
4801   4801       0                                  
4802   4802       0                    Documentary   

                                               homepage      id  \
4798                                                NaN    9367   
4799                                                NaN   72766   
4800  http://www.hallmarkchannel.com/signedsealeddel...  231617   
4801                        http://shanghaicalling.com/  126186   
4802                                                NaN   25975   

                                               keywords original_language  \
4798  united states\u2013mexico barrier legs arms pa...                es   
4799                                                                   en   
4800  date love at first sight narration investigati...                en   
4801                                                                   en   
4802               obsession camcorder crush dream girl                en   

                 original_title  \
4798                El Mariachi   
4799                  Newlyweds   
4800  Signed, Sealed, Delivered   
4801           Shanghai Calling   
4802          My Date with Drew   

                                               overview  popularity  ...  \
4798  El Mariachi just wants to play his guitar and ...   14.269792  ...   
4799  A newlywed couple's honeymoon is upended by th...    0.642552  ...   
4800  "Signed, Sealed, Delivered" introduces a dedic...    1.444476  ...   
4801  When ambitious New York attorney Sam is sent t...    0.857008  ...   
4802  Ever since the second grade when he first saw ...    1.929883  ...   

                                   spoken_languages    status  \
4798  [{"iso_639_1": "es", "name": "Espa\u00f1ol"}]  Released   
4799                                             []  Released   
4800       [{"iso_639_1": "en", "name": "English"}]  Released   
4801       [{"iso_639_1": "en", "name": "English"}]  Released   
4802       [{"iso_639_1": "en", "name": "English"}]  Released   

                                                tagline  \
4798  He didn't come looking for trouble, but troubl...   
4799  A newlywed couple's honeymoon is upended by th...   
4800                                                NaN   
4801                           A New Yorker in Shanghai   
4802                                                NaN   

                          title  vote_average vote_count  \
4798                El Mariachi           6.6        238   
4799                  Newlyweds           5.9          5   
4800  Signed, Sealed, Delivered           7.0          6   
4801           Shanghai Calling           5.7          7   
4802          My Date with Drew           6.3         16   

                                                   cast  \
4798  Carlos Gallardo Jaime de Hoyos Peter Marquardt...   
4799  Edward Burns Kerry Bish\u00e9 Marsha Dietlein ...   
4800  Eric Mabius Kristin Booth Crystal Lowe Geoff G...   
4801  Daniel Henney Eliza Coupe Bill Paxton Alan Ruc...   
4802  Drew Barrymore Brian Herzlinger Corey Feldman ...   

                                                   crew          director  \
4798  [{'name': 'Robert Rodriguez', 'gender': 0, 'de...  Robert Rodriguez   
4799  [{'name': 'Edward Burns', 'gender': 2, 'depart...      Edward Burns   
4800  [{'name': 'Carla Hetland', 'gender': 0, 'depar...       Scott Smith   
4801  [{'name': 'Daniel Hsia', 'gender': 2, 'departm...       Daniel Hsia   
4802  [{'name': 'Clark Peterson', 'gender': 2, 'depa...  Brian Herzlinger   

                                      combined_features  
4798  united states\u2013mexico barrier legs arms pa...  
4799   Edward Burns Kerry Bish\u00e9 Marsha Dietlein...  
4800  date love at first sight narration investi

In [12]:
features =["keywords","cast","genres","director"]

for feature in features:
    df[feature] = df[feature].fillna('')

In [13]:
def combine_feature(row):
  return row["keywords"] +" "+ row["cast"] +" "+ row["genres"] +" "+ row["director"]

df["combined_features"] = df.apply(combine_feature,axis=1)

In [16]:
df.iloc[0]["combined_features"]

'culture clash future space war space colony society Sam Worthington Zoe Saldana Sigourney Weaver Stephen Lang Michelle Rodriguez Action Adventure Fantasy Science Fiction James Cameron'

In [19]:
count_matrix=cv.fit_transform(df["combined_features"])
cosine_model=cosine_similarity(count_matrix)

In [22]:
cosine_model_df=pd.DataFrame(cosine_model,index=df.title,columns=df.title)
cosine_model_df.head()

title                                       Avatar  \
title                                                
Avatar                                    1.000000   
Pirates of the Caribbean: At World's End  0.105409   
Spectre                                   0.120386   
The Dark Knight Rises                     0.037743   
John Carter                               0.230940   

title                                     Pirates of the Caribbean: At World's End  \
title                                                                                
Avatar                                                                    0.105409   
Pirates of the Caribbean: At World's End                                  1.000000   
Spectre                                                                   0.076139   
The Dark Knight Rises                                                     0.035806   
John Carter                                                               0.073030   

title                                      Spectre  The Dark Knight Rises  \
title                                                                       
Avatar                                    0.120386               0.037743   
Pirates of the Caribbean: At World's End  0.076139               0.035806   
Spectre                                   1.000000               0.163572   
The Dark Knight Rises                     0.163572               1.000000   
John Carter                               0.208514               0.039223   

title                                     John Carter  Spider-Man 3  Tangled  \
title                                                                          
Avatar                                       0.230940      0.192450      0.0   
Pirates of the Caribbean: At World's End     0.073030      0.255604      0.0   
Spectre                                      0.208514      0.125109      0.0   
The Dark Knight Rises                        0.039223      0.078446      0.0   
John Carter                                  1.000000      0.200000      0.0   

title                                     Avengers: Age of Ultron  \
title                                                               
Avatar                                                   0.140546   
Pirates of the Caribbean: At World's End                 0.066667   
Spectre                                                  0.190347   
The Dark Knight Rises                                    0.035806   
John Carter                                              0.219089   

title                                     Harry Potter and the Half-Blood Prince  \
title                                                                              
Avatar                                                                  0.082061   
Pirates of the Caribbean: At World's End                                0.116775   
Spectre                                                                 0.088911   
The Dark Knight Rises                                                   0.083624   
John Carter                                                             0.042640   

title                                     Batman v Superman: Dawn of Justice  \
title                                                                          
Avatar                                                              0.117851   
Pirates of the Caribbean: At World's End                            0.111803   
Spectre                                                             0.170251   
The Dark Knight Rises                                               0.120096   
John Carter                                                         0.163299   

title                                     ...  On The Downlow  \
title                                     ...                   
Avatar                                    ...        0.000000   
Pirates of the Caribbean: At World's End  ...        0.000000   
Spectre                

In [38]:
def make_recommendations(movie_user_likes):
    return cosine_model_df[movie_user_likes].sort_values(ascending=False)[:20]
make_recommendations("Avatar")

title
Avatar                             1.000000
Guardians of the Galaxy            0.423390
Aliens                             0.377426
Star Wars: Clone Wars: Volume 1    0.346410
Star Trek Into Darkness            0.344265
Star Trek Beyond                   0.335968
Alien                              0.333333
Lockout                            0.314270
Jason X                            0.307920
The Helix... Loaded                0.288675
Moonraker                          0.285897
Planet of the Apes                 0.281091
Galaxy Quest                       0.280900
Gravity                            0.276520
Alien³                             0.274986
Jupiter Ascending                  0.274986
The Wolverine                      0.269430
Silent Running                     0.269430
Zathura: A Space Adventure         0.264198
Trekkies                           0.264198
Name: Avatar, dtype: float64